/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class Library {
    public boolean someLibraryMethod() {
        new org.example2.Library2();
        return true;
    }
}
